refacto: harmonize all workflows

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -11,12 +11,10 @@ jobs:
         uses: actions/setup-node@v6
         with:
           node-version: 20
-      
-      # Install project dependencies
+
       - name: Install dependencies
         run: npm ci
 
-      # Run Prettier check command
       - name: Run Prettier check
         run: |
           npm run prettier || {
@@ -24,13 +22,13 @@ jobs:
             exit 1
           }
 
-      # Run Stylelint check command
       - name: Run Stylelint check
         run: |
           npm run stylelint || {
             echo "::error::Stylelint check failed. Run 'npm run stylelint:fix' to autofix issues."
             exit 1
           }
+
   eslint:
     name: ESLint
     runs-on: ubuntu-latest
@@ -42,5 +40,12 @@ jobs:
         with:
           node-version: 20
 
-      - name: Lint js
-        run: npm ci && npm run lint
+      - name: Install dependencies
+        run: npm ci
+
+      - name: Run ESLint check
+        run: |
+          npm run lint || {
+            echo "::error::ESLint check failed. Run 'npm run lint:fix' to format your code."
+            exit 1
+          }
